# Site settings
title: "Joel Braun's Resume"
description: "Joel Braun's Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Joel Braun"
resume_title:                   ""

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jb@joelbraun.dev"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p>Strategic thinker and leader with ability to manage project risk and establish value, build collaboration across diverse groups, and drive tight project timelines. I have over 20 years of experience in various technical and developer roles at Freeze.com, W3I, and NativeX. My primary strength is my ability to thoroughly analyze technical issues, remove roadblocks and creatively solve problems through a strategic lens. My passions include development technologies, continuous learning, and establishing strong bidirectional mentoring relationships with my peers and team.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/werelord/"
  # resume_twitter_url:           "http://twitter.com/werelord"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joel-braun-8908904/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://joelbraun.dev"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
